title: title override
url: "https://zvold.github.io"
baseurl: "/test-gh-pages"

theme: jekyll-theme-primer

plugins:
  - jekyll-sitemap
  - jekyll-octicons

markdown: GFM

kramdown:
  input: GFM
  math_engine: mathjax
